### ISSUE TITLE
rev-parse missing treeish:file syntax

### ISSUE THREAD

**Issue by driusan** [driusan/dgit#102]
You should be able to do things like "git rev-parse foo:bar/baz" to refer to the file bar/baz in the tree foo. This isn't parsed correctly and instead looks for a commit named "foo:bar/baz" currently.

**Comment by sirnewton01** [comment]
Does this entail support all of the interesting rev syntax, like HEAD^1 and other constructs?

**Comment by driusan** [comment]
No,  I think those are two different issues with the same command with two very different use cases.
