### ISSUE TITLE
checkoutbranch forcebranch option not implemented

### ISSUE THREAD

**Issue by driusan** [driusan/dgit#105]
In git.CheckoutBranch, the branch option (-b) is implemented but forcebranch (-B) isn't.

Implementing it should just be a matter of checking if the refspec exists before creating the branch, and erroring out if ForceBranch isn't set, but calling UpdateRef if it is.

**Comment by sirnewton01** [comment]
@driusan do you think that this might get us closer to finishing #113?

**Comment by sirnewton01** [comment]
It seems that the -B (force branch) option was already working. I have a PR open to add in some checkout branch tests: #193

**Comment by sirnewton01** [comment]
Unless there is any objection I'm going to close this one as done.

**Comment by driusan** [comment]
Seems like it's working to me too:
