### ISSUE TITLE
Support for local "remote" repositories

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#107]
The official git client supports adding remote repositories that are local filesystem paths. You can fetch from and push to those repositories. Many of the official git tests use local repositories to test push/pull functionality since they are meant to be run in isolation from any remote server.

**Comment by driusan** [comment]
We're also missing support for ssh, and "dumb" http where it just crawls a url and downloads the files.

**Comment by driusan** [comment]
I'll try and tackle this (maybe not the dumb http protocol), it'll give me a break from trying to get all the read-tree tests passing and give me a chance to revisit some of the uglier code I wrote to implement pull back when I didn't understand the transfer protocol at all.

**Comment by driusan** [comment]
I seem to be back on the read-tree campaign, so I'm going to unassign this from myself in case anyone else wants to look into it..

**Comment by driusan** [comment]
I've started adding support for this in #151. The clone/fetch commands still need to be updated to use fetch-pack, and you need a git-upload-pack implementation in your path to clone from a local repo, but that should be fine for running the test suite (once clone/fetch are updated.)

**Comment by driusan** [comment]
Fetching and cloning is done as of #154.

**Comment by driusan** [comment]
With #221 I was able to run `dgit clone . /tmp/foo` on the dgit repo to clone it into /tmp/foo

**Comment by driusan** [comment]
(On DragonFlyBSD)

**Comment by sirnewton01** [comment]
That's awesome. I wonder why the chdir caused problems?

**Comment by driusan** [comment]
It was evaluating paths relative to the wrong place, so the working dir would the new "/tmp/foo" instead of the original "." when it was running fetch and it was detecting that it was already up to date with itself, because it was comparing the new directory to itself.. (it still *looks* like it freezes for a bit, but that's only because for some reason the "git reset --hard" part is slow at the end of the clone)

**Comment by sirnewton01** [comment]
It's definitely working much better now but I'm running into some problems when the dest is not an absolute path. (e.g. git clone foo bar)

```
Rel: can't make bar/foo.txt relative to /Users/cmcgee/tmp
```

**Comment by sirnewton01** [comment]
The t5510-fetch tests are working with the exception of #222 but there is a hang on fetch, not clone now.

**Comment by driusan** [comment]
I'm reverting #221, because I'm getting the same error with http clones, so it needs a little further investigation.

**Comment by sirnewton01** [comment]
Part of this enhancement involves fixing the freezes found in #215 
There is also a freeze happening in "git fetch" when the remote is a local repository, which might be a different problem.

**Comment by driusan** [comment]
Okay, #225 reverts the reversion of #221 with the rel issues more thoroughly tested. can we close this issue and open more specific ones about any issues? The issue that this ticket is about itself is fixed, what's left is other issues that were previously hidden by the fact that the feature didn't work at all..

**Comment by sirnewton01** [comment]
Yes, sounds good. Closing this issue.
