### ISSUE TITLE
Running dgit with no arguments exits with return code 2 instead of 1

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#13]
I am attempting to run the standard git test suite (https://github.com/git/git/tree/master/t) against dgit to see if it can show us the major gaps in the core functionality. I can provide more details if you are interested in running it yourself.

The standard git command will return 1 if you just run 'git' with no arguments, however dgit returns 2 in this case failing some of the tests. The problem seems to be here https://github.com/driusan/dgit/blob/5022e16c8fc449083918d9cce6dbc1895cdaab8d/main.go#L43

When I change that line to return 1 and with some other small work arounds I can run most of the basic git test suite. 32 tests are passing out of 78!

**Comment by driusan** [comment]
You can change any exit codes you want/need. There's no meaning attached to them in dgit other than the usual zero vs non-zero. I just started incrementing them when I started writing the func main() so that I could tell which exit happened. (It looks like I stopped at 4..)

32 out of 78 is better than I expected! Is that only testing the plumbing commands or does it include porcelaine too?

**Comment by sirnewton01** [comment]
I suppose it's debatable whether dgit should have the same exit codes as the standard git command. I'm thinking that if dgit could ever be a drop-in replacement it would need the same codes in case there is automation that relies on them. In this instance, it really helped to be able to run the git test suite if the blank 'git' command returned an exit code of 1.

I'm going through them slowly right now to try to discern which areas are broken. The tests don't appear to be divided nicely into plumbing and porcelain. They seem to be a collection of regression tests for the git developers to catch any problematic changes.

**Comment by driusan** [comment]
In general, unless there's a good reason not too I think dgit should aim for being a drop-in replacement, so the exit codes should match unless there's a reason not to.

**Comment by sirnewton01** [comment]
@driusan if you set up the wiki for this project I can document how to run the git test suite against dgit for future exploration.

**Comment by driusan** [comment]
I added you as a collaborator, I think that should allow you to edit the wiki.

**Comment by sirnewton01** [comment]
Weird, when I click on the wiki tab it doesn't do anything.

**Comment by driusan** [comment]
What about now? I created a stub page.

**Comment by sirnewton01** [comment]
I see your stub page but it seems that I still have no rights to create new pages or edit existing ones.

**Comment by driusan** [comment]
On the Settings page where I would usually change your permissions it says "Invitation link sent".. I suspect GitHub sent you an email that you need to click on before I can edit your permissions on the repo (which the wiki is tied to..)
