### ISSUE TITLE
Pushing regression and unable to set upstream

### ISSUE THREAD

**Issue by henesy** [driusan/dgit#158]
I was previously able to push using dgit, but it seems I can't anymore.

Is there syntax I'm missing? I can't set the upstream either. Various combinations of pushing to origin master, master origin, etc. don't seem to work.

```
tenshi% git push https://github.com/henesy/gfetch
The branch https://github.com/henesy/gfetch has no upstream set.
To push and set the upstream to the remote named "origin" use:

	git push --set-upstream origin https://github.com/henesy/gfetch


tenshi% git push --set-upstream origin https://github.com/henesy/gfetch
The branch https://github.com/henesy/gfetch has no upstream set.
To push and set the upstream to the remote named "origin" use:

	git push --set-upstream origin https://github.com/henesy/gfetch


```

**Comment by driusan** [comment]
does `git push --set-upstream origin branchname` work?

**Comment by henesy** [comment]
`git push --set-upstream origin master` worked. Subsequent `git push master` worked as well. Just not the format I was used to, my apologies.

Should the errors be changed, or something else made to indicate this functionality?

**Comment by driusan** [comment]
The error is the same text string as the error git gives, the difference is that the dgit implementation of push is a bit of a hack and doesn't understand URL remotes properly. I think this will be improved once send-pack is properly implemented in the same way cloning just improved a lot when I just added real support for fetch-pack.

**Comment by driusan** [comment]
(There's also a note about the push syntax not being right in status.txt, which admittedly isn't very obvious but I'm not sure where a better place to put it would be.)
