### ISSUE TITLE
use c.GetConfig consistently

### ISSUE THREAD

**Issue by driusan** [driusan/dgit#162]
The c.GetConfig function was added relatively lately to dgit and is easier to use and faster than using the GitConfig type directly.

Anywhere that looks up config options should be updated to use the new helper.

**Comment by guidopola** [comment]
Hi. This is the first time I try to contribute to a project so I have no idea if it's okay what I did.
I tried to solve the problem, could you check the code?
Thank you

**Comment by driusan** [comment]
Hi @guidopola!

I had a look at the commit referenced above and the code looks reasonable to me, but you need to send it as a pull request so that the test suite gets run on it automatically. See https://help.github.com/articles/creating-a-pull-request/

("git grep ParseConfig" shows a few other places that need to be updated before this issue can be closed, but it's still a step forward, so feel free to send a PR with what you have.)

**Comment by guidopola** [comment]
> There's a little issue with [/cmd/var.go](../tree/2777904e1765f2b005a2667cae07ab7cd7995d07/cmd/var.go#L95) since git.Client's localConfig member is private
> Should I add a function on git.Client to return the local GetConfigList
> `func (c *Client) GetLocalConfigList() []string {
> return c.localConfig.GetConfigList()
> 
> }`
> or leave it as is parsing the file inside the cmd.Var function?

NVM. this is not part of the #162 issue. But i think it could be done to remove the "raw" parsing of gitconfig.

**Comment by driusan** [comment]
I think GetConfig (which is in the right package) should handle the local part already.

**Comment by driusan** [comment]
Resolved by @guidopola in #170 (thanks!)
