### ISSUE TITLE
Segmentation fault when running git config with "--bool" switch

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#17]
Try creating a new git repository.

```
$ git init foo
```

Now change directories into the git repository and getting the core.bare config parameter for it.

```
$ cd foo
$ git config --bool core.bare
```

The command produces a segmentation fault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x123ce9e]

goroutine 1 [running]:
github.com/driusan/dgit/git.(*GitConfig).SetConfig(0xc420065b18, 0x7ffeefbffbeb, 0x6, 0x7ffeefbffbf2, 0x9)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/config.go:56 +0x28e
github.com/driusan/dgit/cmd.Config(0xc4200a6d50, 0xc4200ae0e0, 0x2, 0x2)
	/Users/cmcgee/go/src/github.com/driusan/dgit/cmd/config.go:61 +0x41d
main.main()
	/Users/cmcgee/go/src/github.com/driusan/dgit/main.go:124 +0x249a
```

If you run ```git config --list``` it seems that it can't read any of the configuration parameters.

**Comment by driusan** [comment]
It no longer panics with #30, but following the above instructions now results in "Couldn't find section --bool" since the cmd package doesn't know about the `--bool` option.

**Comment by sirnewton01** [comment]
This should be greatly improved with #40

**Comment by driusan** [comment]
so can this be closed now that #40 is merged or in there still more to do?

**Comment by sirnewton01** [comment]
I think I'd like to use this to get git config --list to work at some point in the future.

**Comment by driusan** [comment]
Okay, I assigned this to you. You can close the issue when you think the flag is sufficiently implemented.

**Comment by sirnewton01** [comment]
I think that I will call this done when #47 is done. There's more to be done in the area of configuration, like the global "-c" flag, supporting multi-tiered configurations, writing global configuration changes. Those can be handled as a separate issue.

**Comment by sirnewton01** [comment]
When #47 is merged another 40 official git tests cases are now passing. :)
