### ISSUE TITLE
'encoding/hex: invalid byte' on clone

### ISSUE THREAD

**Issue by henesy** [driusan/dgit#178]
I found a GitHub repository that makes clone break a bit. Might be worth checking out:

tenshi% git clone https://github.com/ulikunitz/xz
Initialized empty Git repository in /usr/seh/go/src/github.com/ulikunitz/xz/.git/
encoding/hex: invalid byte: U+0076 'v'

**Comment by driusan** [comment]
It's not the repo,  all dgit clones from github are failing right now for the same reason. It looks like github upgraded to support the v2 protocol and there's a couple bugs that it exposed in dgit #179 should make clone work again.
