### ISSUE TITLE
Git archive command missing

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#19]
The git archive command doesn't appear to be present.

**Comment by sirnewton01** [comment]
@driusan I was thinking that we could define some milestones for these issues related to the roadmap. 

I was thinking of these milestones:
* go_get_complete: if we have items that are still needed to make go get work properly in all cases.
* simple_development: for areas that are needed to make simple git collaboration possible
* drop_in_replacement: full drop in replacement of git command-line, most of the official git tests pass

**Comment by driusan** [comment]
What's missing for `go get`?

**Comment by sirnewton01** [comment]
Maybe nothing, but I haven't checked very closely. Do you think there is anything left?

**Comment by driusan** [comment]
I don't know if `go get -u` works, but as far as I know it should work for a plain `go get`

**Comment by sirnewton01** [comment]
@driusan it turns out that simple "go get" is failing after the initial clone, so it appears to work. If you check the exit code it is non-zero because of a submodule command that go get attempts. I'm going to raise a bug on it shortly.
