### ISSUE TITLE
Tag support

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#20]
There is not tag subcommand for creating or querying for tags.

**Comment by sirnewton01** [comment]
@driusan can we call this enhancement done or is the tag support really not complete enough for reasonable use of it?

**Comment by driusan** [comment]
I'd say it's really not done enough. There's no annotated tags at all and the full command line options aren't even parsed. I don't think you can even checkout a tag.

**Comment by sirnewton01** [comment]
Once tags are fully implemented, the show-ref subcommand should be revisited since "go get" uses its output to attempt to check out specific tags for the library based on naming convention in the imports.
