### ISSUE TITLE
Add log support for -n and -format options

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#201]
The new Go 1.11 "go get" with modules is using a special git log command to get the information it needs for setting up git repositories. In particular the -n and -format options of the log subcommand are needed.

**Comment by driusan** [comment]
I think last time I looked into format it was difficult because it had a formatting language embedded which included loops and ifs, but I'm not sure if that was for log or a different subcommand..

**Comment by sirnewton01** [comment]
The full formatting capability is quite comprehensive. For this task, I think we should just add support for a subset including %H, %ct and %D, which are used by "go get."

**Comment by sirnewton01** [comment]
Note that the formatting of commits is supported at the rev-list level as well. It will be good to have this as common functionality that can be shared between different subcommands.

**Comment by sirnewton01** [comment]
This is done.
