### ISSUE TITLE
Fetch is not fetching to a destination specified by the remote.<repoid>.fetch config

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#231]
If you do a ```git fetch``` on a repo with this configuration set assuming you're on the master branch:

```
branch.master.remote <repoid>
remote.<repoid>.url <url_of_repo>
remote.<repoid>.fetch refs/heads/master:refs/heads/somebranch
```

When you fetch, it is expected that the refs/remotes/<repoid>/master is fast-forwarded. But in this case because the destination is specified and 'somebranch' doesn't yet exist it should be created and set to the same commit ID as refs/remotes/heads/master.

**Comment by sirnewton01** [comment]
I'm not sure if this is a bug or an enhancement yet. It's the first test case in t5510-fetch after the setup test that's failing on it.

**Comment by driusan** [comment]
I don't think we support remote.<repoid>.fetch yet, so I think it's an enhancement.

**Comment by sirnewton01** [comment]
There's an alternate way to specify this using a .git/remotes/<repoid> file with contents like the following that specify the fetch behaviour:

```
URL: <repoUrl>
Pull: refs/heads/master:refs/heads/somebranch
```

**Comment by sirnewton01** [comment]
Closing this issue

**Comment by driusan** [comment]
Is it fixed?

**Comment by sirnewton01** [comment]
Yes, it should be fixed now. Some of the official tests cover it, but there are intermittent failures in some of the clones.
