### ISSUE TITLE
Could not find origin/master

### ISSUE THREAD

**Issue by henesy** [driusan/dgit#252]
I'm not sure if this is a real issue or not, but I had a repository somehow end up in a state where it could not find origin/master on git pull.

I can push just fine, and other repositories pull fine, but one I was working in now does not pull.

This might just be something dumb I did and don't remember.

Log: http://okturing.com/src/6786/body

**Comment by driusan** [comment]
There's no file ".git/refs/remotes/origin/master" in the tarball,so neither dgit nor git can push it. I think #253 should prevent it from happening in the future. To fix your local copy, you should be able to just copy `.git/refs/heads/master` onto `.git/refs/remotes/origin/master`

**Comment by henesy** [comment]
Ahhhhhh that makes sense many thanks as always :)

I’ll test my repo soon

**Comment by henesy** [comment]
I can confirm my repo works with quick fix!

I didn't realize this was a thing, thank you :)

**Comment by driusan** [comment]
it was supposed to be created when you did the first git push (or when you do a git clone/fetch), but there was a bug with where `dgit push` didn't create it since you created the repo with `git init`

**Comment by henesy** [comment]
That makes sense ya
