### ISSUE TITLE
Error when providing --porcelain to the status subcommand without a value

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#27]
When invoking ```dgit status --porcelain somedir``` fails with an error where it cannot parse somedir as an integer. The problem is the the porcelain switch is parsed as an IntVar, but in this case it interprets somedir as the value to the porcelain switch. In the standard git the porcelain switch has an optional value and that value _must_ be provided after an equal sign resolving the ambiguity. No value is interpreted to be the value 1.

**Comment by sirnewton01** [comment]
There doesn't appear to be an easy way to get the go flag package to specify that a specific flag value must be provided using an equal sign, otherwise use the default provided in the code.

**Comment by driusan** [comment]
There's a few places on the git command line where the Go flag package isn't sufficient to parse. Another situation is options that can be passed multiple times. (`git commit -m` doesn't use the flag package for that reason) or options that take multiple parameters (ie the space separated variant of`git update-index --cache-info`. rev-list also has a lot of order-sensitive options which I don't think the Go `flag` package is up to parsing.

I don't think there's an easy solution to this.
