### ISSUE TITLE
go get fails due to bitbucket

### ISSUE THREAD

**Issue by halfwit** [driusan/dgit#274]
hg support on bitbucket was blasted away, so we should use the mirror
https://github.com/Plan9-Archive/libauth

**Comment by driusan** [comment]
Thanks for reporting/fixing this.. can't test it right now, but should be fixed by your PR

**Comment by halfwit** [comment]
> Thanks for reporting/fixing this.. can't test it right now, but should be fixed by your PR

Yep, no worries. It seems to build and run correctly on 9front.
