### ISSUE TITLE
cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by 89z** [driusan/dgit#281]
~~~
>  dgit clone https://github.com/89z/rosso
Initialized empty Git repository in D:\Desktop\etc\rosso\.git/
remote: Enumerating objects: 6746, done.
remote: Counting objects: 100% (115/115), done.
remote: Compressing objects: 100% (82/82), done.
Receiving objects: 100% (6746/6746), 1.29 MiB | 1.29 MiB/s, done
Indexing objects: 100% (6746/6746), done
Resolving deltas: 100% (3654/3654), done
rename D:\Desktop\etc\rosso\.git\objects\pack\.tmppackfile1072796690
D:\Desktop\etc\rosso\.git\objects\pack\pack-b46d0b349d5c1d4f40de2b544df2736bdd51a126.pack:
The process cannot access the file because it is being used by another process.
~~~

**Comment by driusan** [comment]
That's odd. Why would another process be accessing a temp file that's generated from dgit? I can't reproduce this right now.. it seems to be specific to Windows, I can clone that repo on Linux. I'll try to get access to a Windows machine and see if I can reproduce.

**Comment by 89z** [comment]
yeah its a Windows issue. If you open a file, even for reading, you cannot move that file until you close it first. So if you have something like this:

~~~
defer file.Close
os.Rename("hello", "world")
~~~

its not going to work

**Comment by 89z** [comment]
yep:

https://github.com/driusan/dgit/blob/1025b7a57236881311b974a2e04cf22411f2675c/git/indexpack.go#L725-L746

**Comment by driusan** [comment]
Can you try putting a `pack.Close()` on line 743 and see if that fixes it?

The defer will still catch the other code paths and since the defer isn't checking the err, calling it twice shouldn't cause any problems.

**Comment by 89z** [comment]
yep, fixes it 😊
