### ISSUE TITLE
What is the mnemonic for this project?

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#41]
I keep trying to think how to pronounce the name of this project.

Is the 'd' silent? Maybe we pronounce the the first letter like dee-git? Another option could be the pronounce it like 'dig-it'?

In any case, I think that we could add a short sentence on the readme for a bit of fun and for clarification. It would be a terrible tragedy for people to have different pronunciations floating around in their heads. "Hmm, Is it Sa - eww - ron or Sore - ron?"

Also, there's a bit of the old name (go-git) floating around in the help docs that could be cleaned up.

**Comment by driusan** [comment]
I pronounce it `dee-git`, but it doesn't really matter to me. The "d" is mostly just to avoid namespace collisions with the official git client and a name that wasn't already taken ("go-git" is a different library and `-` is annoying to type on the command line, `ggit` was already taken and looks like a typo, while `d` is on the home row. easy to type and happens to be the first letter of my name.)

**Comment by sirnewton01** [comment]
Thanks, I'll write up something in a pull request for the readme. It's a bit of silliness, but might help to distinguish the project a little. "Oh, hey there's this new git implementation written in go called dee-git."

**Comment by driusan** [comment]
PR merged
