### ISSUE TITLE
Travis should run parts of real git test suite

### ISSUE THREAD

**Issue by driusan** [driusan/dgit#45]
Since `go test ./...` is so fast, it would be a good idea to also automatically run the (more comprehensive) real git test suite using https://github.com/driusan/dgit/wiki/Verify-dgit-using-official-git-tests for test cases which are known to pass to ensure there are no regressions.

(Currently, t0000-basic.sh is close to passing, but not quite there yet.)

**Comment by sirnewton01** [comment]
I agree that this would be really good to spot regressions or deviations from the official git. I wonder if it might be as simple as issuing an extra couple of script commands (git clone official repo from git tag and then run make) and then travis would just do it.

**Comment by sirnewton01** [comment]
Managed to hook this up to travis. There's only 4 tests out of 77 failing from the t0000-basic test suite.

**Comment by driusan** [comment]
Merged #53
