### ISSUE TITLE
Tests are noisy

### ISSUE THREAD

**Issue by driusan** [driusan/dgit#57]
The magic of SetOutput from main.go doesn't happen with tests, causing them to be noisy.  (There seems to be one log statement generating a lot of the noise, but since the defaults just tell you the time it's not obvious where it is...)

**Comment by sirnewton01** [comment]
I know the place that is causing the noise. I left it in there because I wasn't sure if it added some value to you moving forward or if it was just left in there from a previous debugging session. I can also look into making the logging work better when in the test harness.

**Comment by driusan** [comment]
No, it's just dumping numbers since it's not even casting to a string.

I think to properly fix the test suite we need to add a common test setup function (which we probably should do anyways to do the git init and chdir consistently)

**Comment by driusan** [comment]
(If you don't find an easy solution you can close this since there really bad offender is fixed. )

**Comment by driusan** [comment]
Thanks for fixing it, much easier to read the Travis output now
