### ISSUE TITLE
Add more tests from the official git test suite that are passing

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#63]
After running all of the test suites, looking for ones that are already passing, and filtering those for ones that actually invoke git (not some test tool) here is a list of candidates that could be added to travis to help catch regressions. Each should be vetted for whether it is passing for good reasons and if it will be helpful moving forward.

t0004-unwritable.sh
t0010-racy-git.sh
t0040-parse-options.sh
t0062-revision-walking.sh
t0070-fundamental.sh
t0200-gettext-basic.sh
t1009-read-tree-new-index.sh
t1304-default-acl.sh
t2009-checkout-statinfo.sh
t3070-wildmatch.sh
t3103-ls-tree-misc.sh
t4113-apply-ending.sh
t4123-apply-shrink.sh
t5705-clone-2gb.sh
t7062-wtstatus-ignorecase.sh
t7511-status-index.sh

**Comment by driusan** [comment]
If any of them just invoke git once, I think they're worth adding (even if it's only one or two tests that are valid from each suite.)

**Comment by sirnewton01** [comment]
I have created PR #67 to add a revised list of the suites to travis CI.
