### ISSUE TITLE
Flags can not be glued to the option name

### ISSUE THREAD

**Issue by driusan** [driusan/dgit#82]
The Go `flag` package requires a space separating options from their parameters. The git command line does not. This sometimes comes up in test cases where they do things like `-m"foo"` or `-U0`.

**Comment by sirnewton01** [comment]
I came across the -m case too and patched it for the ignore tests. The documentation that I read seemed to indicate that there must be a space, but yet the official git implementation allows it.

Where is the -U0 option?

**Comment by driusan** [comment]
The `-U0` is in git diff ie here: https://github.com/git/git/blob/master/t/t1002-read-tree-m-u-2way.sh#L82

I'm considering adding a hack for that special case in diff or adding a patch,  but at some point we should try and fix it to be compatible if we can.

**Comment by sirnewton01** [comment]
I'm thinking that we might work around this with some pre-processing of the known args before handing off to flag package to parse replace [... "-U0" ...] with [... "-U", "0", ...]. The documentation won't look quite right, but at least it will work with the official usages.

**Comment by sirnewton01** [comment]
Will this help get us closer to passing the #112 tests?

**Comment by driusan** [comment]
Not to the best of my knowledge, I think the glued flag variants are more common for diff and friends

**Comment by sirnewton01** [comment]
I have a PR #196 open to work around this in commit -m and diff-tree -U.

**Comment by sirnewton01** [comment]
We have an approach for this now that can be handled on a case-by-case basis as there are flags that the official git client supports that are glued. I'm closing this for now.
