### ISSUE TITLE
Missing $home/.gitconfig causes panic during clone

### ISSUE THREAD

**Issue by BurnZeZ** [driusan/dgit#9]
meiling% cd /tmp
meiling% dgit clone https://github.com/driusan/dgit
&{remote origin map[url:https://github.com/driusan/dgit]}&{branch master map[remote:origin]}&{branch master map[remote:origin merge:refs/heads/master]}
Indexing objects:  0% (1/1624)
...
Indexing objects: 100% (1624/1624)Creating /tmp/dgit/.git/refs/remotes/origin/AddGitPush with 506bee2c0fd30c1344421a48d610c454ba22da32Creating /tmp/dgit/.git/refs/remotes/origin/FixBranchCmd with 9d86dddf6f8b023e42fd866f7de92870579fcfbcCreating /tmp/dgit/.git/refs/remotes/origin/RefactorGitReset with 891eb05fd3f30148bc556902445974716624f181Creating /tmp/dgit/.git/refs/remotes/origin/RefactorMergeBase with 52cf23267abdada3559ba04c3d8cf4879b4c83e9Creating /tmp/dgit/.git/refs/remotes/origin/RefixPush with 9eda1f0b964db64966a8ad64869084494fbc8379Creating /tmp/dgit/.git/refs/remotes/origin/master with 8f496b2130264f1bb080f61e46b1f44c4d9666dfpanic: open /usr/glenda/.gitconfig: '/usr/glenda/.gitconfig' does not exist

goroutine 1 [running]:
github.com/driusan/dgit/git.(*Client).GetAuthor(0x420874b70, 0x420a46b00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/glenda/go/src/github.com/driusan/dgit/git/client.go:258 +0x346
github.com/driusan/dgit/git.updateReflog(0x420874b70, 0x420cab601, 0x4216421e0, 0x25, 0x802820, 0x42163fd60, 0x802820, 0x42163fda0, 0x421642180, 0x26, ...)
	/usr/glenda/go/src/github.com/driusan/dgit/git/updateref.go:34 +0xcd
github.com/driusan/dgit/git.UpdateRefSpec(0x420874b70, 0x10000, 0x802820, 0x42163fd60, 0x0, 0x0, 0x0, 0x4ed2b8, 0x11, 0x1b4f2630216b498f, ...)
	/usr/glenda/go/src/github.com/driusan/dgit/git/updateref.go:87 +0x1c2
github.com/driusan/dgit/cmd.Clone(0x420874b70, 0x420874080, 0x1, 0x1, 0xffffffffffffffff, 0x801820)
	/usr/glenda/go/src/github.com/driusan/dgit/cmd/clone.go:74 +0x596
main.main()
	/usr/glenda/go/src/github.com/driusan/dgit/main.go:118 +0x21e5

**Comment by driusan** [comment]
Thanks for reminding me about this.. every time I've discovered it, I ended up setting up the .gitconfig and then forgetting about it.

It should be fixed in master now.
