### ISSUE TITLE
Go get exits with non-zero exit code

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#96]
When writing some go get tests to verify that it is working with dgit I noticed that it is failing, even though the git repo is present. If you check the exit code after go get it is actually non-zero. The reason appears to be that it invokes the submodule subcommand and fails on that.

Here is an excerpt from the go get test script:
```
 cd /home/travis/gopath/src/github.com/golang/protobuf; git submodule update --init --recursive
```

**Comment by driusan** [comment]
Does this only happen with things that use vendoring or does it happen with every repo?

It's kind of annoying, I was hoping to put off implementing submodules for a bit..

**Comment by sirnewton01** [comment]
Ah, that's a good question. It may just be because of the repo I tried testing with. Maybe it's fine with other ones.

**Comment by sirnewton01** [comment]
@driusan there doesn't seem to be any vendor directory or submodules in the protobuf project. I believe that go get just runs this command to update any submodules mentioned in the index if there are any.

What happens today when you clone a repo that has submodules? Will it abort? If so, we can probably get away with stubbing a no-op for this case to make go get work for any repo without submodules, which I believe would be most and rely on the initial clone failing. If not, then to do this properly we will need to implement some level of submodule support.

**Comment by sirnewton01** [comment]
@driusan do you know any GitHub repositories that have submodules that I could try?

**Comment by driusan** [comment]
https://github.com/git/git is the first one that comes to mind.. if you want something smaller,  it should be relatively easy to make a simple test repo with the normal git client

**Comment by sirnewton01** [comment]
#109 satisfies "go get" in that if a module doesn't have any submodules then "submodule init" passes, otherwise fails. Also, "go get" runs the "show-refs" subcommand. The PR implements a stub that just outputs nothing. With these changes "go get" seems to be completely succeeding at least in the majority cases.

**Comment by driusan** [comment]
1. What does `go get` run `show-refs` for?
2. What's the connection between `show-refs` and tags? I thought it's mostly used to show heads.

**Comment by sirnewton01** [comment]
@driusan I checked the go get code and it uses it to find any refs that match a tag like v2. Show-refs can show all refs including tags.

**Comment by driusan** [comment]
Ahh. That makes sense, it must be for vgo.

**Comment by sirnewton01** [comment]
The go get tests are now passing. Unless we can think of other scenarios to test I think we can consider dgit a viable go get alternative to the official git command-line.
